# Generated by Django 5.0 on 2023-12-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name="donor",
            name="has_tattoo",
            field=models.CharField(
                choices=[("", "any tatoo"), ("yes", "Yes"), ("no", "No")], max_length=3
            ),
        ),
    ]
