# Generated by Django 5.0 on 2023-12-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_alter_login_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="login",
            name="phone_number",
            field=models.CharField(default=99999999, max_length=15),
            preserve_default=False,
        ),
    ]
