# Generated by Django 5.0.1 on 2024-01-06 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_delete_login"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wantblood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("", "Select Blood Group"),
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        default="",
                        max_length=3,
                    ),
                ),
                ("phone_no", models.CharField(max_length=10)),
                ("hospitals", models.CharField(max_length=100)),
                (
                    "age",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                18, message="Age cannot be negative"
                            ),
                            django.core.validators.MaxValueValidator(
                                60, message="Age cannot be greater than 60"
                            ),
                        ]
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="donor",
            name="latitude",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="donor",
            name="longitude",
            field=models.CharField(max_length=255),
        ),
    ]
